  - name: install ansible dependencies
    apt: name={{ item }} state=present
    with_items:
      - python-boto
      - python-bz2file

  - name: compress current wordpress site
    shell: tar -cjvf /tmp/{{ site_backup_filename }} /var/www/html
    args:
      creates: /tmp/{{ site_backup_filename }}

  - name: send site backup to S3
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: the-mast
      object: "{{ backup_prefix }}/{{ ansible_date_time.epoch }}-site_backup.tar.bz2"
      mode: put
      region: eu-west-1
      src: /tmp/{{ site_backup_filename }}

  - name: dump wp_options
    shell: mysqldump wordpress wp_options | bzip2 >/tmp/{{ wp_options_backup_filename }} 
    args:
      creates: /tmp/{{ wp_options_backup_filename }}

  - name: send options backup to S3
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: the-mast
      object: "{{ backup_prefix }}/{{ ansible_date_time.epoch }}-wp_options_backup-{{ansible_hostname}}.tar.bz2"
      mode: put
      region: eu-west-1
      src: /tmp/{{ wp_options_backup_filename }}

  - name: dump sql database
    mysql_db:
      state: dump
      name: all
      target: /tmp/{{ sql_backup_filename }}

  - name: send sql backup to S3
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: the-mast
      object: "{{ backup_prefix }}/{{ ansible_date_time.epoch }}-sql_backup.bz2"
      mode: put
      region: eu-west-1
      src: /tmp/{{ sql_backup_filename }}
