  - name: get database dump
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: the-mast
      object: "/last-release/sql_backup-{{data_env}}.bz2"
      mode: get
      region: eu-west-1
      dest: /tmp/datadump.sql.bz2

  - name: unzip the datadump
    shell: bzip2 -d /tmp/datadump.sql.bz2

  - name: get uploads
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: the-mast
      object: "/last-release/site_uploads_backup-{{data_env}}.tar.bz2"
      mode: get
      region: eu-west-1
      dest: /tmp/uploads.tar.bz2

  - name: get presson-theme
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: the-mast
      object: "/last-release/presson-theme-staging.tar.bz2"
      mode: get
      region: eu-west-1
      dest: /tmp/presson-theme.tar.bz2
