---
- name: ensure theme directory exists
  file:
    dest: "{{ wordpress_installs[0].path }}/wp-content/themes/{{ wp_theme.name }}"
    state: directory
    
- name: download && install default specified wordpress theme
  unarchive:
    src: "{{ wp_theme.url }}"
    copy: no
    remote_src: yes
    extra_opts: ['--strip-components=1', '--show-stored-names']
    dest: "{{ wordpress_installs[0].path }}/wp-content/themes/{{ wp_theme.name }}"
    group: www-data
    owner: www-data

- name: add SSL settings for reverse proxy
  blockinfile:
    dest: "{{ wordpress_installs[0].path }}/wp-config.php"
    insertbefore: "^// \\*\\* MySQL settings \\*\\* //"
    block: |
        define('FORCE_SSL_ADMIN', true);
        if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false)
        $_SERVER['HTTPS']='on';
