---
- hosts: all
  become: yes

  pre_tasks:
    - name: common dependencies
      apt: name={{ item }} state=latest
      with_items:
        - rsync
        - zip

    - name: install wordpress dependencies
      apt: name={{ item }} state=latest
      with_items:
        - mariadb-server
        - php
        - apache2
        - libapache2-mod-php
        - php7.0-mysql
        - python-mysqldb

    - name: enable apache modules
      apache2_module: name={{ item }}
      with_items:
        - php7.0
        - rewrite

    - name: remove default index.html
      file: path=/var/www/html/index.html state=absent

    - name: install database
      mysql_db: name=wordpress state=present

    - name: create user
      mysql_user:
        name: wordpress
        password: "{{ vars.wordpress_installs[0].dbpass }}"
        priv: 'wordpress.*:ALL'
        state: present

  post_tasks:
    - name: restart apache
      service: name=apache2 state=restarted

  roles:
    - role: tersmitten.wordpress
      notify: restart apache

  vars:
    wordpress_installs:
      - name: wordpress
        dbname: wordpress
        dbuser: wordpress
        dbpass: 'heCrE7*d2KEs'
        dbhost: localhost
        path: /var/www/html
        url: http://localhost:8080
        title: wordpress
        admin_name: dev
        admin_email: dev@localhost.localdomain
        admin_password: 'dev.password'
        themes:
          - name: the-mast-theme
            activate: true
        plugins: []
        users: {}
        options: []
        queries: []

