---
- hosts: "*:!loadbalancer"
  become: yes

  vars_files:
    - "./vars/{{ ansible_host | default('vagrant') }}.yml"

  pre_tasks:
    - debug: msg="Configuring the following host - {{ ansible_host}}"

    - name: common dependencies
      apt: name={{ item }} state=latest
      with_items:
        - rsync
        - zip

    - name: download & install theme if not on vagrant box (local)
      include: tasks/wp_theme.yml
      when: ansible_host

  roles:
    - role: database
      dbhost: "{{ wordpress_installs[0].dbhost}}"
      dbname: "{{ wordpress_installs[0].dbname }}"
      dbuser: "{{ wordpress_installs[0].dbuser }}"
      dbpass: "{{ wordpress_installs[0].dbpass }}"

    - role: webserver

    - role: tersmitten.wordpress
      notify: restart apache
