---
- hosts: "*:!loadbalancer"
  become: yes

  vars_files:
    - "./vars/{{ inventory_hostname | default('vagrant') }}.yml"

  pre_tasks:
    - debug: msg="Configuring the following host - {{ ansible_host}}"

    - name: common dependencies
      apt: name={{ item }} state=latest
      with_items:
        - rsync
        - unzip

    - name: download & install theme if not on vagrant box (local)
      include: tasks/wp_theme.yml
      when: inventory_hostname != None

  post_tasks:
    - name: add SSL settings for reverse proxy
      blockinfile:
        dest: "{{ wordpress_installs[0].path }}/wp-config.php"
        insertbefore: "^// \\*\\* MySQL settings \\*\\* //"
        block: |
          define('FORCE_SSL_ADMIN', true);
          if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false)
          $_SERVER['HTTPS']='on';

  roles:
    - role: database
      dbhost: "{{ wordpress_installs[0].dbhost}}"
      dbname: "{{ wordpress_installs[0].dbname }}"
      dbuser: "{{ wordpress_installs[0].dbuser }}"
      dbpass: "{{ wordpress_installs[0].dbpass }}"

    - role: tersmitten.wordpress
      notify: restart apache

    - role: webserver