#switching
#
---
- hosts: webservers
  vars_files:
    - "vars/webserver.yml"

  tasks:
    - name: adjust urls appropriately
      include: tasks/adjust_urls.yml

- hosts: loadbalancer
  roles:
    - role: loadbalancer
      TLS_EMAIL: 'the-mast@thoughtworks.com'
      SITE_DOMAIN: 'themastonline.com'

  tasks:
    - name: restart caddy
      service: name=caddy state=restarted
