#switching
#
---
- hosts: production
  vars:
    siteurl: "{{ 'https://www.themastonline.com' if 'production' in group_names else 'https://staging.themastonline.com' }}"

  vars_files:
    - "vars/webserver.yml"

  tasks:
    - name: adjust siteurl appropriately
      command: wp-cli option --allow-root --no-color --path="{{wordpress_installs[0].path}}" update "siteurl" "{{siteurl}}"

    - name: adjust home appropriately
      command: wp-cli option --allow-root --no-color --path="{{wordpress_installs[0].path}}" update "home" "{{siteurl}}"

- hosts: loadbalancer
  roles:
    - role: loadbalancer
      TLS_EMAIL: 'the-mast@thoughtworks.com'
      SITE_DOMAIN: 'themastonline.com'

  tasks:
    - name: restart caddy
      service: name=caddy state=restarted
