#switching
#
---
- hosts: loadbalancer
  roles:
    - role: loadbalancer
      TLS_EMAIL: 'the-mast@thoughtworks.com'
      SITE_DOMAIN: 'themastonline.com'

  tasks:
    - name: restart caddy
      service: name=caddy state=restarted
