---
- name: allow overrides
  blockinfile: 
    dest: /etc/apache2/sites-enabled/000-default.conf
    insertafter: "<VirtualHost \\*:80>"
    block: |
        <Directory /var/www/html>
            AllowOverride All
        </Directory>

- name: enable mode rewrite rules
  copy:
    dest: /var/www/html/.htaccess
    src: htaccess
