---
- name: install fail2ban
  apt: name=fail2ban state=present

- name: download wordpress filters
  shell: curl https://plugins.svn.wordpress.org/wp-fail2ban/trunk/filters.d/wordpress-hard.conf > /etc/fail2ban/filter.d/wordpress.conf

- name: apply the wordpress fail2ban config
  copy:
    dest: /etc/fail2ban/jail.d/wordpress.conf
    src: wordpress.fail2ban.conf

- name: install & activate fail2ban wordpress plugin
  command: wp-cli --allow-root --no-color --path='/var/www/html' plugin install --activate wp-fail2ban

- name: add SSL settings for reverse proxy
  lineinfile:
    dest: "{{ wordpress_installs[0].path }}/wp-config.php"
    insertbefore: "^// \\*\\* MySQL settings \\*\\* //"
    line: "define('WP_FAIL2BAN_PROXIES','{{ hostvars['loadbalancer']['ansible_host'] }}');"

- name: restart fail2ban
  service: name=fail2ban state=restarted