---
- name: install wordpress dependencies
  apt: name={{ item }} state=latest
  with_items:
    - php
    - apache2
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-gd
    - curl

- name: enable apache modules
  apache2_module: name={{ item }}
  with_items:
    - php7.0
    - rewrite

- name: remove default index.html
  file: path=/var/www/html/index.html state=absent

- name: configure apache
  include: configuration.yml

- name: apply fail2ban plugin
  include: fail2ban.yml
  when: install_fail2ban

- name: set permissions
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('www-data') }}"
    group: "{{ item.group | default(item.owner) | default('www-data') }}"
    mode: 0755
    recurse: true
  with_items: "{{ wordpress_installs }}"