---
- name: install ansible dependencies
  apt: name='python-mysqldb' state=present

- name: install MariaDB
  apt: name=mariadb-server state=latest

- name: install database
  mysql_db: login_host="{{ dbhost }}" name="{{ dbname }}" state=present

- name: create user
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: "{{ dbname | trim }}.*:ALL"
    state: present