# playbook to to backup wordpress
# From the provision/ directory, run the following command
# source env.sh && ansible-playbook playbooks/backup_wordpress.yml -i hosts.ini -l [blue,green]
---
- hosts: webservers

  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    backup_prefix: "/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/{{ ansible_date_time.day }}"
    site_backup_filename: "{{ ansible_date_time.epoch }}-site_backup.tar.bz2"
    sql_backup_filename: "{{ ansible_date_time.epoch }}-sql_backup.sql.bz2"
    wp_uploads_backup_filename: "{{ ansible_date_time.epoch }}-wp_uploads_backup.tar.bz2"
    backup_postfix: "{{ 'production' if 'production' in group_names else 'staging'}}"

  tasks:
    - name: install ansible dependencies
      apt: name={{ item }} state=present
      with_items:
        - python-boto
        - python-bz2file
  
    - name: compress current wordpress site
      shell: tar -cjvf /tmp/{{ site_backup_filename }} /var/www/html
      args:
        creates: /tmp/{{ site_backup_filename }}
  
    - name: send site backup to S3
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "{{ backup_prefix }}/{{ ansible_date_time.epoch }}-{{config_name}}-{{ansible_hostname}}-site_backup.tar.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/{{ site_backup_filename }}
  
    - name: send site backup to S3 in last-release
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "/{{config_name}}-last-release/site_backup-{{backup_postfix}}.tar.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/{{ site_backup_filename }}
  
    - name: compress current wordpress uploads
      shell: tar -cjvf /tmp/{{ wp_uploads_backup_filename}} /var/www/html/wp-content/uploads
      args:
        creates: /tmp/{{ wp_uploads_backup_filename }}
  
    - name: send site uploads backup to S3
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "{{ backup_prefix }}/{{ ansible_date_time.epoch }}-{{config_name}}-{{ansible_hostname}}-site_uploads_backup.tar.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/{{ wp_uploads_backup_filename }}
  
    - name: send site uploads backup to S3 in last-release
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "/{{config_name}}-last-release/site_uploads_backup-{{backup_postfix}}.tar.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/{{ wp_uploads_backup_filename }}
  
    - name: dump sql database
      mysql_db:
        state: dump
        name: all
        target: /tmp/{{ sql_backup_filename }}
  
    - name: send sql backup to S3
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "{{ backup_prefix }}/{{ ansible_date_time.epoch }}-{{config_name}}-{{ansible_hostname}}-sql_backup.sql.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/{{ sql_backup_filename }}
  
    - name: send sql backup to S3 last-release
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "/{{config_name}}-last-release/sql_backup-{{backup_postfix}}.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/{{ sql_backup_filename }}

  post_tasks:
    - name: delete temporary site backup file
      file:
          state: absent
          path: "/tmp/{{ site_backup_filename }}"

    - name: delete temporary site uploads backup file
      file:
          state: absent
          path: "/tmp/{{ wp_uploads_backup_filename }}"

    - name: delete temporary database backup file
      file:
          state: absent
          path: "/tmp/{{ sql_backup_filename }}"
  
    - name: compress current wordpress theme
      shell: tar -cjvf /tmp/presson-theme.tar.bz2 /var/www/html/wp-content/themes/presson-theme
      args:
        creates: /tmp/presson-theme.tar.bz2
  
    - name: send presson-theme to s3 last-release
      s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: the-mast
        object: "/{{config_name}}-last-release/presson-theme-{{backup_postfix}}.tar.bz2"
        mode: put
        region: eu-west-1
        src: /tmp/presson-theme.tar.bz2
