# playbook to to backup wordpress
# From the provision/ directory, run the following command
# source env.sh && ansible-playbook playbooks/backup_wordpress.yml -i hosts.ini -l [blue,green]
---
- hosts: webservers

  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    backup_prefix: "/{{ ansible_date_time.year }}/{{ ansible_date_time.month }}/{{ ansible_date_time.day }}"
    site_backup_filename: "{{ ansible_date_time.epoch }}-site_backup.tar.bz2"
    sql_backup_filename: "{{ ansible_date_time.epoch }}-sql_backup.sql.bz2"
    wp_uploads_backup_filename: "{{ ansible_date_time.epoch }}-wp_uploads_backup.tar.bz2"

  tasks:
    - name: backup
      include: ../tasks/backup.yml
