- hosts: webservers

  vars_files:
    - "./vars/{{ 'production' if 'production' in group_names else 'staging' }}.yml"

  tasks:
    - name: set the database to readonly
      include: ../tasks/setDatabaseToReadonly.yml
